version: '3'
services:
  cryptovote1:
    image: nelo/cryptovote
    container_name: cryptovote1
    environment:
      #ASPNETCORE_URLS: http://*:80
      NodeName: cryptovote1 
      #NodeId: 95125E7E-A6FF-45AC-B359-BE371721E7E1 
      MinerInterval: 5000 
      MinerAddress: PXikqz1jNKw4hKticmNsvnwBNdpmBUJZWGbiPz7cQ3t8f2y1Qgcz431eanuUcqazirjuaoWJ6cjpLvXEENguQ5UK
      NodePublicUrl: http://cryptovote1/
      BlockchainDificulty: 2
      PeerUrl: http://cryptovote2/
    ports:
      - 8081:80
    networks:
    - cryptonet

  cryptovote2:
    image: nelo/cryptovote
    container_name: cryptovote2
    environment:
      #ASPNETCORE_URLS: http://*:80
      NodeName: cryptovote2 
      #NodeId: 95125E7E-A6FF-45AC-B359-BE371721E7E2
      MinerInterval: 5000 
      MinerAddress: QMiBLQnRDJCf2v7DwATbq46f8o9XZkua9GKeq4wucJW6SqQ6pQ3zBzBjoXt8G76AJvFHeRva7bUv1qg23McRH4GB
      NodePublicUrl: http://cryptovote2/
      BlockchainDificulty: 2
      PeerUrl: http://cryptovote3/
    ports:
      - 8082:80
    networks:
    - cryptonet

  cryptovote3:
    image: nelo/cryptovote
    container_name: cryptovote3
    environment:
      #ASPNETCORE_URLS: http://*:80
      NodeName: cryptovote3
      #NodeId: 95125E7E-A6FF-45AC-B359-BE371721E7E3
      MinerInterval: 5000 
      MinerAddress: QCWderiVdAVDLTxipfHnRY7gmpAU8sdC9pd5NQmkd8eDjMyPC2haiVjZDqaEi7xDrAQzk91FMRrT82TGu1GwWaCZ
      NodePublicUrl: http://cryptovote3/
      BlockchainDificulty: 2
      PeerUrl: http://cryptovote1/
    ports:
      - 8083:80
    networks:
    - cryptonet

networks:
  cryptonet: