version: '3'
services:
  cryptovote1:
    image: nelo/cryptovote
    container_name: cryptovote1
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      NodeName: cryptovote1 
      #NodeId: 95125E7E-A6FF-45AC-B359-BE371721E7E1 
      MinerInterval: 60000 
      MinerAddress: QXuwUXRhANuouMkHTc2tbcZhkcucShZQKEhs7XSfseSd6Rq8q2G3sSZc1Q1z5jdj4Nz8dQuieiiyDVLiKWDmtJVp
      NodePublicUrl: http://cryptovote1:5000/
      BlockchainDificulty: 2
      PeerUrl: http://cryptovote2:5000
    ports:
      - 8001:80
    networks:
    - cryptonet

  cryptovote2:
    image: nelo/cryptovote
    container_name: cryptovote2
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      NodeName: cryptovote2 
      #NodeId: 95125E7E-A6FF-45AC-B359-BE371721E7E2
      MinerInterval: 5000 
      MinerAddress: QXuwUXRhANuouMkHTc2tbcZhkcucShZQKEhs7XSfseSd6Rq8q2G3sSZc1Q1z5jdj4Nz8dQuieiiyDVLiKWDmtJVp
      NodePublicUrl: http://cryptovote2:5000/
      BlockchainDificulty: 2
      PeerUrl: http://cryptovote3:5000
    ports:
      - 8002:80
    networks:
    - cryptonet

  cryptovote3:
    image: nelo/cryptovote
    container_name: cryptovote3
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      NodeName: cryptovote3
      #NodeId: 95125E7E-A6FF-45AC-B359-BE371721E7E3
      MinerInterval: 17000 
      MinerAddress: QXuwUXRhANuouMkHTc2tbcZhkcucShZQKEhs7XSfseSd6Rq8q2G3sSZc1Q1z5jdj4Nz8dQuieiiyDVLiKWDmtJVp
      NodePublicUrl: http://cryptovote3:5000/
      BlockchainDificulty: 2
      PeerUrl: http://cryptovote1:5000
    ports:
      - 8003:80
    networks:
    - cryptonet

networks:
  cryptonet: