FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY ./Core.sln .
COPY ./CryptoVote/*.csproj ./CryptoVote/
COPY ./Domain/*.csproj ./Domain/
RUN dotnet restore

# copy everything else and build app
COPY ./CryptoVote/. ./CryptoVote/
COPY ./Domain/. ./Domain/

WORKDIR /app/CryptoVote
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/CryptoVote/out ./
ENTRYPOINT ["dotnet", "CryptoVote.dll"]